# Data Preprocessing part 3

In [17]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler,StandardScaler,RobustScaler
from category_encoders import OneHotEncoder
df=pd.read_csv("data/raw/Titanic.csv")

In [18]:
X=df.drop(columns=['Survived'])
y=df[['Survived']]

In [19]:
display(X.head())
display(y.head())

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

   Survived
0         0
1         1
2         1
3         1
4         0

## If you have outliers don't use MinMax and Z-Score SCALERS
## Use Robust Scaler x-median / IQR to avoid the affect of outliers 
## You have more techniques like L1 , L2 NORM
## what is the diff between fit , transform and fit_transform and what is the role of it in prevent data lackage

In [20]:
num_cols=X.select_dtypes('number').columns


scaler=MinMaxScaler()
display(X[num_cols])
scaler.fit(X[num_cols])
X[num_cols]=scaler.transform(X[num_cols])
display(X[num_cols])

     PassengerId  Pclass   Age  SibSp  Parch     Fare
0              1       3  22.0      1      0   7.2500
1              2       1  38.0      1      0  71.2833
2              3       3  26.0      0      0   7.9250
3              4       1  35.0      1      0  53.1000
4              5       3  35.0      0      0   8.0500
..           ...     ...   ...    ...    ...      ...
886          887       2  27.0      0      0  13.0000
887          888       1  19.0      0      0  30.0000
888          889       3   NaN      1      2  23.4500
889          890       1  26.0      0      0  30.0000
890          891       3  32.0      0      0   7.7500

[891 rows x 6 columns]

     PassengerId  Pclass       Age  SibSp     Parch      Fare
0       0.000000     1.0  0.271174  0.125  0.000000  0.014151
1       0.001124     0.0  0.472229  0.125  0.000000  0.139136
2       0.002247     1.0  0.321438  0.000  0.000000  0.015469
3       0.003371     0.0  0.434531  0.125  0.000000  0.103644
4       0.004494     1.0  0.434531  0.000  0.000000  0.015713
..           ...     ...       ...    ...       ...       ...
886     0.995506     0.5  0.334004  0.000  0.000000  0.025374
887     0.996629     0.0  0.233476  0.000  0.000000  0.058556
888     0.997753     1.0       NaN  0.125  0.333333  0.045771
889     0.998876     0.0  0.321438  0.000  0.000000  0.058556
890     1.000000     1.0  0.396833  0.000  0.000000  0.015127

[891 rows x 6 columns]

## Label Encoding : used to encode target values  in classification
# search diff between target encoding and label encoding 
## Nominal low:(onehotencoder) , high (hash , frequence encoder, binary encoder) and ordinal (ordinal class for encoding) features , search about lingustic variables

In [ ]:
str_cols=["Sex","Embarked"]

encoder=OneHotEncoder(cols=str_cols,drop_invariant=True)
x=encoder.fit_transform(X)